// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFq_czupJ7ieeyYGTuv_ciOPgWalmlzB0',
    appId: '1:773300433762:web:7ebf435a1ca90b3469b23b',
    messagingSenderId: '773300433762',
    projectId: 'ramzy-pharmacy',
    authDomain: 'ramzy-pharmacy.firebaseapp.com',
    storageBucket: 'ramzy-pharmacy.firebasestorage.app',
    measurementId: 'G-Q7DJVLLCQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSvFuKjOeItJq0Cyakczrl_L56Bj3g2M',
    appId: '1:773300433762:android:bab1b2a1aaad098d69b23b',
    messagingSenderId: '773300433762',
    projectId: 'ramzy-pharmacy',
    storageBucket: 'ramzy-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY0AudjllRk3Uk4AgXZxEJKj3AyzJRn6k',
    appId: '1:773300433762:ios:b53e303cce2cd99169b23b',
    messagingSenderId: '773300433762',
    projectId: 'ramzy-pharmacy',
    storageBucket: 'ramzy-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.pharmacy',
  );
}
